/*
* SPDX-FileCopyrightText: Copyright 2019 - 2020 | CSI Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
/**
 * Contabilità passiva
 * API per il backend della suite di contabilità passiva.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Settore } from './settore';
import { StatoElOrdine } from './statoElOrdine';
import { StatoNso } from './statoNso';
import { TestataOrdine } from './testataOrdine';


export interface Destinatario { 
    id?: string;
    progressivo?: number;
    cap?: string;
    contatto?: string;
    dataInvioNso?: Date;
    email?: string;
    indirizzo?: string;
    localita?: string;
    numCivico?: string;
    provincia?: string;
    statoNso?: StatoNso;
    telefono?: string;
    statoElOrdine?: StatoElOrdine;
    testataOrdine?: TestataOrdine;
    settore?: Settore;
    optlock?: string;
}
