/*
* SPDX-FileCopyrightText: Copyright 2019 - 2020 | CSI Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
/**
 * Contabilità passiva
 * API per il backend della suite di contabilità passiva.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CausaleSospensioneEvasione } from './causaleSospensioneEvasione';
import { Impegno } from './impegno';
import { ImpegnoOrdine } from './impegnoOrdine';
import { RigaEvasione } from './rigaEvasione';
import { SubimpegnoEvasione } from './subimpegnoEvasione';


export interface ImpegnoEvasione { 
    causaleSospensioneEvasione?: CausaleSospensioneEvasione;
    dataCancellazione?: Date;
    dataCreazione?: Date;
    dataModifica?: Date;
    dataSospensione?: Date;
    id?: string;
    impegno?: Impegno;
    impegnoAnno?: number;
    impegnoAnnoEsercizio?: number;
    impegnoNumero?: number;
    impegnoOrdine?: ImpegnoOrdine;
    impegnoProgressivo?: number;
    importoLiquidato?: number;
    importoRipartito?: number;
    importoSospeso?: number;
    optlock?: string;
    rigaEvasione?: RigaEvasione;
    subimpegnoEvasiones?: Array<SubimpegnoEvasione>;
    totaleRipartibile?: number;
    utenteCancellazione?: string;
    utenteCreazione?: string;
    utenteModifica?: string;
}
