/*
* SPDX-FileCopyrightText: Copyright 2019 - 2020 | CSI Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
/**
 * Contabilità passiva
 * API per il backend della suite di contabilità passiva.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AliquoteIva } from './aliquoteIva';
import { Cpv } from './cpv';
import { UnitaMisura } from './unitaMisura';


export interface Ods { 
    id?: number;
    inventariabile?: boolean;
    codice?: string;
    descrizione?: string;
    dataValiditaFine?: Date;
    dataValiditaInizio?: Date;
    prezzoUnitario?: number;
    aliquoteIva?: AliquoteIva;
    cpv?: Cpv;
    unitaMisura?: UnitaMisura;
}
