/*
* SPDX-FileCopyrightText: Copyright 2019 - 2020 | CSI Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
/**
 * Contabilità passiva
 * API per il backend della suite di contabilità passiva.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AliquoteIva } from './aliquoteIva';
import { Cpv } from './cpv';
import { ListinoFornitore } from './listinoFornitore';
import { UnitaMisura } from './unitaMisura';


export interface OggettiSpesa { 
    aliquoteIva?: AliquoteIva;
    codice?: string;
    cpv?: Cpv;
    dataCancellazione?: Date;
    dataCreazione?: Date;
    dataModifica?: Date;
    dataValiditaFine?: Date;
    dataValiditaInizio?: Date;
    descrizione?: string;
    id?: string;
    inventariabile?: number;
    listinoFornitores?: Array<ListinoFornitore>;
    optlock?: string;
    prezzoUnitario?: number;
    unitaMisura?: UnitaMisura;
    utenteCancellazione?: string;
    utenteCreazione?: string;
    utenteModifica?: string;
}
