/*
* SPDX-FileCopyrightText: Copyright 2019 - 2020 | CSI Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
/**
 * Contabilità passiva
 * API per il backend della suite di contabilità passiva.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ImpegnoOrdine } from './impegnoOrdine';
import { Subimpegno } from './subimpegno';


export interface SubimpegnoOrdine { 
    dataCancellazione?: Date;
    dataCreazione?: Date;
    dataModifica?: Date;
    id?: string;
    impegnoAnno?: number;
    impegnoAnnoEsercizio?: number;
    impegnoNumero?: number;
    impegnoOrdine?: ImpegnoOrdine;
    optlock?: string;
    subimpegno?: Subimpegno;
    subimpegnoAnno?: number;
    subimpegnoImporto?: number;
    subimpegnoNumero?: number;
    utenteCancellazione?: string;
    utenteCreazione?: string;
    utenteModifica?: string;
}
