/*
* SPDX-FileCopyrightText: Copyright 2019 - 2020 | CSI Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
/**
 * Contabilità passiva
 * API per il backend della suite di contabilità passiva.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CausaleSospensioneEvasione } from './causaleSospensioneEvasione';
import { DocumentoTrasporto } from './documentoTrasporto';
import { ImpegnoEvasione } from './impegnoEvasione';
import { Subimpegno } from './subimpegno';
import { SubimpegnoOrdine } from './subimpegnoOrdine';


export interface SubimpegnoEvasione { 
    documentoTrasporto?: DocumentoTrasporto;
    id?: string;
    impegnoAnno?: number;
    impegnoAnnoEsercizio?: number;
    impegnoEvasione?: ImpegnoEvasione;
    impegnoNumero?: number;
    importoLiquidato?: number;
    importoRipartito?: number;
    importoSospeso?: number;
    subimpegno?: Subimpegno;
    subimpegnoAnno?: number;
    subimpegnoNumero?: number;
    subimpegnoOrdine?: SubimpegnoOrdine;
    totaleRipartibile?: number;
    dataSospensione?: Date;
    optlock?: string;
    causaleSospensioneEvasione?: CausaleSospensioneEvasione;
}
