/*
* SPDX-FileCopyrightText: Copyright 2019 - 2020 | CSI Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
/**
 * Contabilità passiva
 * API per il backend della suite di contabilità passiva.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiError } from '../model/apiError';
import { Elaborazione } from '../model/elaborazione';


import { Configuration }                                     from '../configuration';


export interface ElaborazioneServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;
    

    /**
    * 
    * ottiene una lista di elaborazioni per id entità.
    * @param id L&#39;id dell&#39;entity.
    */
    getElaborazioniByEntity(id: string, extraHttpRequestParams?: any): Observable<Array<Elaborazione>>;

    /**
    * 
    * Inserisce una elaborazione sul sistema.
    * @param elaborazione 
    */
    postElaborazione(elaborazione: Elaborazione, extraHttpRequestParams?: any): Observable<Elaborazione>;

}
